/** @type {import('tailwindcss').Config} */
export default {
	darkMode: "class",
	content: ["./index.html", "./src/**/*.{js,jsx}"],
	theme: {
		screens: {
			xs: "480px",
			sm: "640px",
			md: "768px",
			lg: "1024px",
			xl: "1280px",
			"2xl": "1536px",
		},
		extend: {
			colors: {
				"outline-variant": "#464555",
				"on-primary": "#1d00a5",
				"inverse-primary": "#4d44e3",
				"surface-bright": "#39393b",
				"on-primary-fixed-variant": "#3323cc",
				"on-primary-fixed": "#0f0069",
				"on-tertiary-container": "#ffd2be",
				surface: "#0e0e10",
				"on-tertiary": "#571f00",
				outline: "#918fa1",
				error: "#ffb4ab",
				secondary: "#89ceff",
				"on-tertiary-fixed-variant": "#7b2f00",
				"on-tertiary-fixed": "#351000",
				"surface-variant": "#1b1b1d",
				"secondary-container": "#00a2e6",
				"secondary-fixed": "#c9e6ff",
				"surface-dim": "#0e0e10",
				"inverse-surface": "#e5e1e4",
				"error-container": "#93000a",
				"surface-container-high": "#201f21",
				"tertiary-fixed-dim": "#ffb695",
				"surface-tint": "#c3c0ff",
				"inverse-on-surface": "#303032",
				"secondary-fixed-dim": "#89ceff",
				"primary-fixed": "#e2dfff",
				"on-primary-container": "#dad7ff",
				"on-secondary-container": "#00344e",
				"on-secondary-fixed-variant": "#004c6e",
				"on-secondary-fixed": "#001e2f",
				"primary-container": "#4f46e5",
				"surface-container": "#131315",
				"on-surface": "#f1f1f3",
				"on-error-container": "#ffdad6",
				background: "#0e0e10",
				"on-secondary": "#00344d",
				"surface-container-highest": "#2a2a2c",
				"tertiary-fixed": "#ffdbcc",
				"on-error": "#690005",
				primary: "#c3c0ff",
				"surface-container-low": "#131315",
				"primary-fixed-dim": "#c3c0ff",
				tertiary: "#ffb695",
				"on-surface-variant": "#c7c4d8",
				"tertiary-container": "#a44100",
				"on-background": "#e5e1e4",
				"surface-container-lowest": "#050505",
			},
			borderRadius: {
				DEFAULT: "0.25rem",
				lg: "0.5rem",
				xl: "0.75rem",
				full: "9999px",
			},
			spacing: {
				gutter: "24px",
				"container-max": "1280px",
				"margin-mobile": "20px",
				"margin-desktop": "64px",
				unit: "8px",
				"section-gap": "120px",
			},
			fontFamily: {
				"headline-lg-mobile": ["Inter"],
				"headline-lg": ["Inter"],
				display: ["Inter"],
				"body-lg": ["Inter"],
				"body-md": ["Inter"],
				caption: ["Inter"],
				"headline-md": ["Inter"],
				"label-md": ["Inter"],
			},
			fontSize: {
				"headline-lg-mobile": [
					"32px",
					{ lineHeight: "1.2", fontWeight: "700" },
				],
				"headline-lg": [
					"48px",
					{ lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" },
				],
				display: [
					"64px",
					{ lineHeight: "1.1", letterSpacing: "0.04em", fontWeight: "800" },
				],
				"body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
				"body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
				caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
				"headline-md": ["30px", { lineHeight: "1.3", fontWeight: "600" }],
				"label-md": [
					"14px",
					{ lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "600" },
				],
			},
		},
	},
	plugins: [
		require("@tailwindcss/forms"),
		require("@tailwindcss/container-queries"),
	],
};
